// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ContosoConsultancy.Rest.Client.ContosoConsultancyRest.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ContosoConsultancyRestModelsDashboardMissionModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ContosoConsultancyRestModelsDashboardMissionModel class.
        /// </summary>
        public ContosoConsultancyRestModelsDashboardMissionModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ContosoConsultancyRestModelsDashboardMissionModel class.
        /// </summary>
        public ContosoConsultancyRestModelsDashboardMissionModel(long? id = default(long?), long? consultantId = default(long?), long? customerId = default(long?), string consultantFullName = default(string), string customer = default(string), string country = default(string), DateTime? startDate = default(DateTime?))
        {
            Id = id;
            ConsultantId = consultantId;
            CustomerId = customerId;
            ConsultantFullName = consultantFullName;
            Customer = customer;
            Country = country;
            StartDate = startDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ConsultantId")]
        public long? ConsultantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerId")]
        public long? CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ConsultantFullName")]
        public string ConsultantFullName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Customer")]
        public string Customer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartDate")]
        public DateTime? StartDate { get; set; }

    }
}
