// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ContosoConsultancy.Rest.Client.ContosoConsultancyRest.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ContosoConsultancyRestModelsConsultantsSearchConsultantModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ContosoConsultancyRestModelsConsultantsSearchConsultantModel
        /// class.
        /// </summary>
        public ContosoConsultancyRestModelsConsultantsSearchConsultantModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ContosoConsultancyRestModelsConsultantsSearchConsultantModel
        /// class.
        /// </summary>
        public ContosoConsultancyRestModelsConsultantsSearchConsultantModel(string name = default(string), string firstName = default(string), string teamName = default(string))
        {
            Name = name;
            FirstName = firstName;
            TeamName = teamName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TeamName")]
        public string TeamName { get; set; }

    }
}
