// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ContosoConsultancy.Rest.Client.ContosoConsultancyRest.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ContosoConsultancyRestModelsConsultantsConsultantModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ContosoConsultancyRestModelsConsultantsConsultantModel class.
        /// </summary>
        public ContosoConsultancyRestModelsConsultantsConsultantModel() { }

        /// <summary>
        /// Initializes a new instance of the
        /// ContosoConsultancyRestModelsConsultantsConsultantModel class.
        /// </summary>
        public ContosoConsultancyRestModelsConsultantsConsultantModel(long? id = default(long?), string name = default(string), string firstName = default(string), DateTime? birthDate = default(DateTime?), DateTime? hireDate = default(DateTime?), DateTime? disengagedDate = default(DateTime?), ContosoConsultancyRestModelsSharedResourceReference teamReference = default(ContosoConsultancyRestModelsSharedResourceReference))
        {
            Id = id;
            Name = name;
            FirstName = firstName;
            BirthDate = birthDate;
            HireDate = hireDate;
            DisengagedDate = disengagedDate;
            TeamReference = teamReference;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BirthDate")]
        public DateTime? BirthDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HireDate")]
        public DateTime? HireDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DisengagedDate")]
        public DateTime? DisengagedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TeamReference")]
        public ContosoConsultancyRestModelsSharedResourceReference TeamReference { get; set; }

    }
}
