// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ContosoConsultancy.Rest.Client.ContosoConsultancyRest.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CustomerModel
    {
        /// <summary>
        /// Initializes a new instance of the CustomerModel class.
        /// </summary>
        public CustomerModel() { }

        /// <summary>
        /// Initializes a new instance of the CustomerModel class.
        /// </summary>
        public CustomerModel(long? id = default(long?), string name = default(string), int? numberOfMissions = default(int?), string country = default(string))
        {
            Id = id;
            Name = name;
            NumberOfMissions = numberOfMissions;
            Country = country;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumberOfMissions")]
        public int? NumberOfMissions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; set; }

    }
}
