// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ContosoConsultancy.Rest.Client.ContosoConsultancyRest.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResourceReference
    {
        /// <summary>
        /// Initializes a new instance of the ResourceReference class.
        /// </summary>
        public ResourceReference() { }

        /// <summary>
        /// Initializes a new instance of the ResourceReference class.
        /// </summary>
        public ResourceReference(long? id = default(long?), string href = default(string))
        {
            Id = id;
            Href = href;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Href")]
        public string Href { get; private set; }

    }
}
