// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ContosoConsultancy.Rest.Client.ContosoConsultancyRest.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SystemCollectionsGenericKeyValuePairSystemInt32SystemInt32
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SystemCollectionsGenericKeyValuePairSystemInt32SystemInt32 class.
        /// </summary>
        public SystemCollectionsGenericKeyValuePairSystemInt32SystemInt32() { }

        /// <summary>
        /// Initializes a new instance of the
        /// SystemCollectionsGenericKeyValuePairSystemInt32SystemInt32 class.
        /// </summary>
        public SystemCollectionsGenericKeyValuePairSystemInt32SystemInt32(int? key = default(int?), int? value = default(int?))
        {
            Key = key;
            Value = value;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public int? Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public int? Value { get; set; }

    }
}
