// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ContosoConsultancy.Rest.Client.ContosoConsultancyRest.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TeamModel
    {
        /// <summary>
        /// Initializes a new instance of the TeamModel class.
        /// </summary>
        public TeamModel() { }

        /// <summary>
        /// Initializes a new instance of the TeamModel class.
        /// </summary>
        public TeamModel(long? id = default(long?), string name = default(string), ResourceReference manager = default(ResourceReference), IList<ResourceReference> members = default(IList<ResourceReference>))
        {
            Id = id;
            Name = name;
            Manager = manager;
            Members = members;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Manager")]
        public ResourceReference Manager { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Members")]
        public IList<ResourceReference> Members { get; set; }

    }
}
